VirtualCity_Work_YourOffice_MapScripts::
	.byte 0










VirtualCity_Work_YourOffice_Text_MinhACTIPonytaDone1:
	.string "I think… I think that should do it.$"


VirtualCity_Work_YourOffice_Text_SophieACTIPonytaDone2:
	.string "It's done? How is he?$"

VirtualCity_Work_YourOffice_Text_MinhACTIPonytaDone3:
	.string "Ex is fine, don't worry. It's like\n"
	.string "changing your Realm avatar.\p"
	.string "He might have to learn how to walk on\n"
	.string "four feet, though!$"

VirtualCity_Work_YourOffice_Text_SophieACTIPonytaDone4:
	.string "Wow, he looks great!\n"
	.string "Ex, you feeling okay?$"

VirtualCity_Work_YourOffice_Text_SophieACTIPonytaDone5:
	.string "Oh, he's fine! He knows he's about to\n"
	.string "get to fight! Don't you, cutie?\p"
	.string "And Minh, you were worried about not\n"
	.string "being helpful!\p"
	.string "No other artist could have edited Ex\n"
	.string "into a Ponyta so fast and accurately!\p"

VirtualCity_Work_YourOffice_Text_MinhACTIPonytaDone6:
	.string "Oh, stop it! …but do go on!\p"
	.string "Ahem. You should be able to get into\n"
	.string "the IRL Department now.\p"
	.string "See if you can find some evidence of\n"
	.string "the IRL Pokemon being made there!$"

VirtualCity_Work_YourOffice_Text_MinhACTIPonytaDoneRepeat:
	.string "Ex doing okay? I'll change him back\n"
	.string "as soon as you're done.\p"
	.string "Remember, you gotta get into the IRL\n"
	.string "department with Ex and find evidence.\l"
	.string "that they're making fake Pokemon!$"



VirtualCity_Work_YourOffice_Text_MinhACTIOutro1:
	.string "You're back! What did you find?$"

VirtualCity_Work_YourOffice_Text_SophieACTIOutro2:
	.string "…$"

VirtualCity_Work_YourOffice_Text_MinhACTIOutro3:
	.string "It's an unfinished Ponyta…\n"
	.string "Hi, lil' guy!$"

VirtualCity_Work_YourOffice_Text_SophieACTIOutro4:
	.string "Let get back to the outside.\n"
	.string "I bet this Ponyta comes with us.\p"
	.string "That means… it's like Lola's Snubbull.$"

VirtualCity_Work_YourOffice_Text_MinhACTIOutro5:
	.string "A virtual Pokemon being sold as a\n"
	.string "real one. Let's go check.$"

