OutsideWorld_ApartmentBldg1_YourApartment_MapScripts::
	.byte 0



OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk1Minh::
	.string "Hey, sorry we're late!$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk2Harriet::
	.string "Aaah, finally! Lola, come on, we've\n"
	.string "been waiting for so long!$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk3Ernest::
	.string "To be fair… she's been waiting…\n"
	.string "for twenty-two… years.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk4Lola::
	.string "…\p"
	.string "It's been a long time.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk5Lola::
	.string "You all know better than anyone how\n"
	.string "much I wanted a real Pokemon.\p"
	.string "So many people called it a stupid,\n"
	.string "unrealistic dream.\p"
	.string "Back then, I couldn't explain why it\n" 
	.string "felt so… uh, necessary?\p"
	.string "Actually, I still can't explain it.\n"
	.string "But just look at him!$"
	
OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk6Lola::
	.string "Go on, pet him! Like you would a\n"
	.string "VR Pokemon. He's super friendly!\p"
	.string "And you'll understand it.\n"
	.string "Why real Pokemon are so important.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk7Harriet::
	.string "Whoa, his fur! It feels like a blanket!$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk8Ernest::
	.string "What's… his name, Lola?$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk9Lola::
	.string "Dreams. Dreams the Snubbull.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk10Lola::
	.string "Hey, don't be shy, you two!\p"
	.string "You're all going to be his aunts and\n"
	.string "uncles, come say hi!$"


OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk11Minh::
	.string "…\p"
	.string "Um, hi there Dreams. Lola's going to\n"
	.string "take very good care of you!$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk12Sophie::
	.string "Yes, she will. It…\n"
	.string "Ahem, welcome to our little group?$"	


OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk13Lola::
	.string "Don't worry, Dreams, I'm sure they'll\n"
	.string "be less shy tomorrow. Now come on,\l"
	.string "you haven't even seen your bed yet!$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk14Lola::
	.string "See y'all tomorrow!$"




OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk15Harriet::
	.string "It was so cute! And I've never seen\n"
	.string "Lola so happy!$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk16Ernest::
	.string "No one deserves it more than Lola.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk17Ernest::
	.string "Hey, what's the matter? Minh? Sophie?$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk18Minh::
	.string "Sophie? You…$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk19Sophie::
	.string "It's nothing.\n"
	.string "We've just had a long day at work.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk20Harriet::
	.string "Ah, no worries. Anyways, I gotta jet.\n"
	.string "Let's celebrate with Lola tomorrow!$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk21Ernest::
	.string "Hm.\p"
	.string "I know something's up.\n"
	.string "Tell me about it later.$"


OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk22Minh::
	.string "Sophie? You… you saw it too?$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk23Sophie::
	.string "I saw it.\p"
	.string "There's… there's no doubt.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk24Minh::
	.string "The eyes… they were wrong.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk25Sophie::
	.string "The mouth, too.\p"
	.string "That's… that's not a real Snubbull.\p"
	.string "It looked… drawn.\p"
	.string "Like the VR Pokemon you design…\n"
	.string "but not as skillful.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk25Minh::
	.string "Are you saying… does BETTER have a\n"
	.string "way to make fake IRL Pokemon?!\p"
	.string "And Lola just spent her life savings\n"
	.string "on one, thinking it was real?!$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk26Sophie::
	.string "Minh.\p"
	.string "There's something here even worse than\n"
	.string "Lola getting scammed.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk27Sophie::
	.string "Are there even any real Pokemon left?$"


@Scene transition to sitting on couches bleakly, not facing each other


OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk28Sophie::
	.string "There's no point brooding any longer.\p"
	.string "It's late, you should get home. Meet in\n"
	.string "the Realm, at work, when you can.\p"
	.string "At least that way, Lola won't be\n"
	.string "able to hear us talking about it.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk29Minh::
	.string "…I don't know what we're going to do.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk30Sophie::
	.string "We're going to find out who's doing\n"
	.string "this. And we're going to get evidence.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk31Minh::
	.string "…Okay.\p"
	.string "Whoever it is, they've got artists.\n"
	.string "I'll ask around with my art friends.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_IntroTalk29Minh::
	.string "Good plan. I'll see you tomorrow.$"





@@ ACT II INTRO

OutsideWorld_ApartmentBldg1_YourApartment_Text_SophieActIIIntro1::
	.string "Harriet. Ernest. Thanks for coming.\n"
	.string "We don't have long until Lola gets home.\p"
	.string "Minh and I have some news.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_ErnestActIIIntro2::
	.string "What, are you dating?$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_SophieActIIIntro3::
	.string "What? No!\n"
	.string "It's very bad news, Ernest!$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_HarrietActIIIntro4::
	.string "What? What is it?\n"
	.string "Sophie, you're shaking!$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_SophieActIIIntro5::
	.string "When Lola showed us her Snubbull, Minh\n"
	.string "and I both noticed something wrong.\p"
	.string "So we did some digging… and…$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_HarrietActIIIntro6::
	.string "What? You got one? How did you afford…$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_HarrietActIIIntro7::
	.string "Aaaah! What is… Why is it unfinished?!$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_MinhActIIIntro8::
	.string "Because it's not real. BETTER has a way\n"
	.string "to make IRL fakes now, somehow.\p"
	.string "And they're being sold as real.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_ErnestActIIIntro9::
	.string "Fakes? You mean, Lola's Snubbull isn't\n"
	.string "a real flesh-and-blood Pokemon?$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_SophieActIIIntro10::
	.string "Yeah. And Minh and I are going to do\n"
	.string "something about it.$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_MinhActIIIntro11::
	.string "What Sophie means is that she wanted\n"
	.string "to go in guns blazing.\p"
	.string "I managed to convince her that you two\n"
	.string "would want to help.\p"
	.string "(And help me stop her from doing\n"
	.string "something really dangerous.)$"

OutsideWorld_ApartmentBldg1_YourApartment_Text_SophieActIIIntro12::
	.string "We can't talk here, Lola's gonna be back\n"
	.string "soon. Meet at my place in the Realm.$"






