OutsideWorld_Traveling_MapScripts::
	.byte 0





OutsideWorld_Traveling_Text_IntroTalk3Minh::
	.string "My grandma was a trainer! So I got to\n"
	.string "see loads of Pokemon as a child!\p"
	.string "That's part of how I got the artist\n"
	.string "job, actually. I'm working off of real\l"
	.string "experience, not just photos!$"

OutsideWorld_Traveling_Text_IntroTalk4Sophie::
	.string "You're so lucky...$"

OutsideWorld_Traveling_Text_IntroTalk5Minh::
	.string "Lola's the lucky one. And we all\n"
	.string "get to be aunts and uncles!$"
