OutsideWorld_Traveling_MapScripts::
	.byte 0



OutsideWorld_Traveling_Text_IntroTalk1::
	.string "When was the last time you saw a\n"
	.string "Pokemon, you know, in real life?$"

OutsideWorld_Traveling_Text_IntroTalk2::
	.string "Gosh, I don't even remember.\p"
	.string "It must have been when I was a child,\n"
	.string "before the zoo closed down.\p"
	.string "What about you?$"

OutsideWorld_Traveling_Text_IntroTalk3::
	.string "My grandma was a trainer! So I got to\n"
	.string "see loads of Pokemon as a child!\p"
	.string "That's part of how I got the artist\n"
	.string "job, actually. I'm working off of real\l"
	.string "experience, not just photos!$"

OutsideWorld_Traveling_Text_IntroTalk4::
	.string "You're so lucky...$"

OutsideWorld_Traveling_Text_IntroTalk5::
	.string "Katya's the lucky one. I hope she\n"
	.string "lets us play with it!$"