VirtualCity_Hotel_YourRoom_MapScripts::
	.byte 0




VirtualCity_Hotel_YourRoom_Text_ResolutionTalk1Minh::
	.string "We have to do something.\p"
	.string "Pokemon are being replaced with fakes\n"
	.string "and no one else knows.$"

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk2Ernest::
	.string "You two work on VR Pokemon - you can\n"
	.string "see the signs that we can't.\p"
	.string "But what can we even do?$"

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk3Harriet::
	.string "Corpo will just censor us, or worse,\n"
	.string "if we try to tell people.$"

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk4Sophie::
	.string "…\p"
	.string "I'm going to get the word out somehow.\n"
	.string "No matter what happens.$"

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk5Minh::
	.string "Sophie! Let's think about this!$"

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk6Harriet::
	.string "Sophie, even you wouldn't want a\n" 
	.string "repeat of the Rare Candy incident…$"

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk7Sophie::
	.string "It's not going to be like that.\n" 
	.string "We'll do it right.$"

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk8Sophie::
	.string "We can't fight the corpo -\n" 
	.string "they're just too powerful.$" 

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk9Sophie::
	.string "We can't boycott them -\n" 
	.string "they're everywhere.$" 

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk10Sophie::
	.string "We can't save any real Pokemon\n" 
	.string "that might be out there.$" 

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk11Sophie::
	.string "But maybe we can do something.\n"
	.string "Something small.\p"
	.string "We're all very good at what we do…\p"
	.string "If you three are in, I bet we could do$"
	.string "something to expose this.$"

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk12Minh::
	.string "If we can figure out a plan, I'm in.\p"
	.string "How many Lolas are out there?$"

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk13Harriet::
	.string "I doubt we'll be able to do much,\n"
	.string "but I'll help if I can.$"

VirtualCity_Hotel_YourRoom_Text_ResolutionTalk14Ernest::
	.string "It would have to be anonymous…\p"
	.string "Where could we put a message that\n"
	.string "everyone could see, that couldn't be\l"
	.string "traced back to us?$"


@@
